version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: seenimurugan/docker-spring-boot-rest-service:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 2GB
      restart_policy:
        condition: on-failure
    ports:
      - "4000:8080"
    networks:
      - webnet
networks:
  webnet: