version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: seenimurugan/docker-spring-boot-rest-service:latest
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.2"
          memory: 5000M
      restart_policy:
        condition: on-failure
    ports:
      - "4001:8080"
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet: